import {t} from 'i18next'

export const NUMBERS = {
  CONST_ZERO: t('Const_zero'),
  CONST_ONE: t('Const_one'),
  CONST_FOUR: t('Const_four'),
  CONST_FIVE: t('Const_five'),
  CONST_SIX: t('Const_six')
}

export const COMMON = {
  COLUMN_FLEX: 0.25,
  COLUMN_FLEX_SMALL: 0.15,
  COLUMN_MIN_WIDTH: 200,
  COLUMN_MIN_WIDTH_SMALL: 100,
  COLUMN_ACTION_FLEX: 0.125,
  COLUMN_ACTION_MIN_WIDTH: 100,
  FORM_MARGIN_TOP: '6px',
  ACTION_ICON_MARGIN: '5px',
  ACTIONS_FIELD: 'actions',
  ACTIONS_TEXT_VARIANT: 'body2',
  ACTIONS_TEXT_COLOR: '#6495ED',
  ACTIONS_TEXT_CURSOR: 'pointer',
  BUTTON_PRIMARY_COLOR: 'primary',
  BACK_BUTTON_VARIANT: 'outlined',
  SAVE_BUTTON_VARIANT: 'contained',
  DELETE_BUTTON_VARIANT: 'contained',
  MODAL_DELETE_TEXT_VARIANT: 'body2'
}

export const CATALOGS = {
  TABLE_PAGE_SIZE: 5,
  TABLE_PAGE_ROWS_OPTIONS: [7, 10, 25, 50],
  DIMENSIONS_FIELD_FLEX_SIZE: 12,
  DIMENSIONS_FIELD_NAME: 'name',
  CONCEPTS_FIELD_NAME: 'name',
  CONCEPTS_FIELD_TYPE: 'type',
  CONCEPTS_FIELD_DEFINITION: 'definition',
  CONCEPTS_FIELD_OBSERVATIONS: 'observations',
  CONCEPTS_FIELD_VARIABLE_NAME: 'variableName',
  CONCEPTS_FIELD_VARIABLE_ID: 'variablesID',
  VARIABLES_FIELD_NAME: 'name',
  VARIABLES_FIELD_OBLIGATION: 'obligation',
  VARIABLES_FIELD_SPECIFICATIONS: 'specifications',
  VARIABLES_FIELD_GUIDELINES: 'guidelines',
  VARIABLES_FIELD_SERVICE: 'service',
  VARIABLES_FIELD_DIMENSIONS_NAME: 'dimensionName',
  VARIABLES_FIELD_DIMENSION_ID: 'dimensionID'
}

export const MAINTENANCES = {
  TABLE_PAGE_SIZE: 5,
  TABLE_PAGE_ROWS_OPTIONS: [7, 10, 25, 50],
  MAINTENANCES_FIELD_FLEX_SIZE: 12,
  MAINTENANCES_FIELD_NAME: 'name'
}
